###
GET http://localhost:4000

###
GET http://localhost:4000/roaster

###
GET http://localhost:4000/roaster/2

###
DELETE  http://localhost:4000/roaster/2

###
POST  http://localhost:4000/roaster
Content-Type: application/json

{
    "first_name": "fernando",
    "last_name": "castro",
    "age": 19
}

###
PATCH  http://localhost:4000/roaster/1
Content-Type: application/json

{
    "first_name": "luna",
    "last_name": "chavez",
    "age": 19
}